---
- name: restart ypserv
  service: 
    name: ypserv 
    state: restarted

- name: restart rpcbind
  service: 
    name: rpcbind 
    state: restarted

- name: restart yppasswdd
  service: 
    name: yppasswdd 
    state: restarted

- name: config firewall rules
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop:
    - "{{ ypserv_port }}/tcp"
    - "{{ ypserv_port }}/udp"
    - "{{ ypxfrd_port }}/tcp"
    - "{{ ypxfrd_port }}/udp"
    - "{{ yppasswdd_port }}/udp"
