---
- name: restart autofs
  service:
    name: autofs
    state: restarted
    enabled: true

- name: config firewall rules
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop:
    - nfs
    - rpc-bind
    - mountd
